# Generated by Django 3.2.7 on 2021-09-11 00:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_alter_ventaproducto_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ventaproducto',
            name='usuario',
        ),
    ]
