# Generated by Django 3.2.7 on 2021-09-11 01:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('sales', '0005_remove_ventaproducto_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='ventaproducto',
            name='usuario',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='users.profile'),
            preserve_default=False,
        ),
    ]
