# Generated by Django 3.2.7 on 2021-09-11 01:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompraGeneral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('articulo_total', models.BigIntegerField(default=0, editable=False)),
                ('metodo_pago', models.CharField(blank=True, choices=[('EFECTIVO', 'EFECTIVO'), ('TARJETA', 'TARJETA'), ('MIXTO', 'MIXTO')], default='EFECTIVO', max_length=100, verbose_name='METODO')),
                ('fc', models.DateTimeField(auto_now_add=True)),
                ('total', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=50)),
                ('total_efectivo', models.FloatField(default=0, editable=False)),
                ('total_tarjeta', models.FloatField(default=0, editable=False)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CompraProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(default=0)),
                ('venta', models.FloatField(default=0, editable=False)),
                ('importe', models.FloatField(default=0, editable=False)),
                ('num_venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopping.comprageneral')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos_nombre', to='products.product')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.profile')),
            ],
        ),
    ]
