# Generated by Django 3.2.7 on 2021-09-11 01:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='precio',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator('0.0')]),
        ),
    ]
