# Generated by Django 3.2.7 on 2021-09-11 01:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_precio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='precio',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator('0.0')]),
        ),
    ]
