# Generated by Django 3.2.7 on 2021-09-11 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_product_precio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='precio',
            field=models.FloatField(default=0),
        ),
    ]
